Update manage-policies.html.md
hashicorp/terraform-website pull request #1599
Opened 2021-01-19 21:14 UTC by susiesolis

## Labels

- [ ] inaccuracy
- [ ] clarification
- [ ] new docs
- [ ] cosmetic bug - fixing broken text or markup
- [ ] enhancement - changing the website's behavior/layout

2021-01-19 21:17 UTC, vancluever commented
Hey @susiesolis, I think this is only really necessary when using GitHub. Maybe add a note mentioning to do this when using GitHub?

2021-01-20 00:54 UTC, vancluever commented
@susiesolis can you also add how someone views a raw file within a particular page in GH too?

2021-01-20 18:49 UTC, susiesolis commented
> @susiesolis can you also add how someone views a raw file within a particular page in GH too?

@vancluever - updated it. Can you verify that it looks okay?

2021-01-20 19:49 UTC, vancluever requested changes
Just a couple of minor edits and it should be good!

2021-01-20 19:49 UTC, vancluever commented on content/source/docs/cloud/sentinel/manage-policies.html.md
> +"https://github.com/hashicorp/terraform-foundational-policies-library/master/cis/aws/networking/aws-cis-4.1-networking-deny-public-ssh-acl-rules/aws-cis-4.1-networking-deny-public-ssh-acl-rules.senti
```suggestion
`https://github.com/hashicorp/terraform-foundational-policies-library/master/cis/aws/networking/aws-cis-4.1-networking-deny-public-ssh-acl-rules/aws-cis-4.1-networking-deny-public-ssh-acl-rules.sentinel` will give a hard error when the policy is checked. To access the raw URL, select the Sentinel file that you wish to link to in the Github repository. Once the Sentinel file is open, right click on the **Raw** button on the top right of the page, and save the link address.
```

2021-01-20 19:51 UTC, justinretzolk approved these changes
After the previously suggested changes, this looks good to me!

2021-01-22 17:24 UTC, merged