Add note for unsupported Postgres SSL connection parameters
hashicorp/terraform-website pull request #1619
Opened 2021-02-04 02:31 UTC by hashitop

## Labels

- [X] inaccuracy
- [X] clarification
- [ ] new docs
- [ ] cosmetic bug - fixing broken text or markup
- [ ] enhancement - changing the website's behavior/layout

2021-02-04 18:31 UTC, justinretzolk approved these changes
Looks good to me. Added @sudomateo to double check, as I'm unfamiliar with these parameters. Approving so I'm not the hold up.

2021-02-04 18:32 UTC, justinretzolk requested changes
On second though, these commas are unnecessary IMO.

2021-02-04 18:32 UTC, justinretzolk commented on content/source/docs/enterprise/before-installing/postgres-requirements.html.md
> +-> **Note:** See the PostgreSQL library documentation for more about [extra parameters related to sslmode](https://www.postgresql.org/docs/9.6/libpq-ssl.html). Terraform Enterprise provides a certifi
```suggestion
-> **Note:** See the PostgreSQL library documentation for more about [extra parameters related to sslmode](https://www.postgresql.org/docs/9.6/libpq-ssl.html). Terraform Enterprise provides a certificates file at `/tmp/cust-ca-certificates.crt`, which is required by the `verify-full` and `verify-ca` modes. Additional certificates can be added via the [CA Custom Bundle](../install/installer.html#certificate-authority-ca-bundle) setting, however, Terraform Enterprise currently does **not** support the client-side certificate parameters `sslcert` and `sslkey`.
```

2021-02-05 07:28 UTC, hashitop commented
as per section 31.18.2, https://www.postgresql.org/docs/9.5/libpq-ssl.html

2021-02-05 18:00 UTC, sudomateo requested changes
Thank you for submitting this!

Instead of the current approach, I think you should create another note beneath the existing note specifying that verification of client certifications is not supported. Then link to section 
"32.18.2. Client Certificates" on [this page](https://www.postgresql.org/docs/9.6/libpq-ssl.html).

2021-02-07 22:05 UTC, hashitop commented
@sudomateo is this ok?

![image](https://user-images.githubusercontent.com/50546939/107160819-abc5d700-69ec-11eb-9015-6219a2690810.png)

2021-02-08 05:20 UTC, sudomateo commented
@hashitop Looks good to me!

2021-02-08 05:34 UTC, hashitop commented
Thank you!

2021-02-08 06:05 UTC, hashitop reviewed
Thank you!

2021-02-08 06:06 UTC, hashitop commented
A few commits above due to the conflict in itself
I am going to squash it in now

2021-02-08 06:08 UTC, merged