Update index.html.md
hashicorp/terraform-website pull request #1622
Opened 2021-02-09 15:36 UTC by Galser

We had several customers stepping on S3 test problem in ReplicatedUI dashboard during config phase , perhaps it should be outlined  here, in our manual.

The source of the information is here : https://help.replicated.com/docs/config-screen/test-procs/#aws-auth

> Feel free to decline if you feel that this is more suited for KB artilce in Support

2021-02-09 15:58 UTC, nervda requested changes
**Note:** During the interactive installation Replicated (TFE setup dashboard) can execute S3 access tests that will be performed using `ListAllMyBuckets` action. And, as a result - require additional permission added *temporarily* to the policy above - **ListAllMyBuckets**. Later, in operations Terraform Enterprise not require this permission.

2021-02-09 20:27 UTC, sudomateo requested changes
Thank you for working on this! Submitted a suggestion.

2021-02-09 20:27 UTC, sudomateo commented on content/source/docs/enterprise/before-installing/index.html.md
> +-> **Note:** During the interactive installation Replicated (TFE setup dashboard) can execute S3 access tests that will be perfomed using `ListAllMyBuckets` action. And, as a result - require additio
We can be a bit more brief here.

```suggestion
-> **Note:** The `s3:ListAllMyBuckets` permission is necessary when testing authentication via the Replicated web console. However, the permission is not required for Terraform Enterprise to function and can be removed once the authentication is successfully tested.
```

2021-02-10 07:53 UTC, merged

2021-02-10 16:17 UTC, sudomateo commented
@Galser This should not have been merged without an approval. Just an FYI for next time.