Update active-active.html.md
hashicorp/terraform-website pull request #1755
Opened 2021-07-01 16:08 UTC by sudomateo

## Labels

- [x] inaccuracy
- [ ] clarification
- [ ] new docs
- [ ] cosmetic bug - fixing broken text or markup
- [ ] enhancement - changing the website's behavior/layout
- [ ] api - requires an update to the [changelog](https://www.terraform.io/docs/cloud/api/changelog.html)

2021-07-13 14:40 UTC, laurapacilio requested changes
Thank you for adding! I'm not reviewing for content accuracy, but I did review for style and flow. I added a couple of suggestions for your review - please make sure that my edits didn't unintentionally change the meaning!

2021-07-13 14:40 UTC, laurapacilio commented on content/source/docs/enterprise/admin/active-active.html.md
> +This command will generate a support bundle for all nodes. The support bundles will be uploaded to the same object store bucket that is used to store Terraform statefiles. The support bundles for a s
It's cleaner without "will" and also this matches the construction we have below :-) 

```suggestion
This command generates a support bundle for all nodes. The support bundles will be uploaded to the same object store bucket that is used to store Terraform state files. The support bundles for a specific run of the admin command will all be uploaded to a directory with the same JobID (a timestamp in [RFC3339](https://datatracker.ietf.org/doc/html/rfc3339) format). If you are sending a support bundle to HashiCorp Support, package and send all associated bundles to ensure that we have all the necessary information.
```

2021-07-13 14:40 UTC, laurapacilio commented on content/source/docs/enterprise/admin/active-active.html.md
> +This command allows users to make ad hoc/realtime application changes, such as `capacity_concurrency` via the CLI. Both an allowable `<KEY>` (setting name) and `<VALUE>` (new setting value) must be p
Some updates for active voice and also to help the text flow a bit better. For example, I love that you included steps to restart TFE, and I wanted to help the users parse them more quickly by using a numbered list.
```suggestion
This command allows you to use the CLI to make real-time application changes, such as `capacity_concurrency`. You must provide both an allowable `<KEY>` (setting name) and `<VALUE>` (new setting value). Run `replicatedctl app-config export` for a complete list of the current `app-config` settings. 

For the configuration changes to take effect, you must restart the Terraform Enterprise application **on each node instance**. To restart Terraform Enterprise:
1. Run `replicatedctl app stop` to stop the application. 
2. Run `replicatedctl app status` to confirm the application is stopped. 
3. Run `replicatedctl app start` to start the application.
```

2021-07-14 00:37 UTC, sudomateo commented
Thank you for the review! Implemented!

2021-07-14 12:46 UTC, laurapacilio approved these changes

2021-07-14 12:46 UTC, laurapacilio commented
Nice - thank you! :-) Feel free to merge whenever!

2021-07-15 14:26 UTC, merged