Update azure.md - no redis cluster protocol support for a successful …
hashicorp/terraform-website pull request #1774
Opened 2021-07-15 11:04 UTC by dwaiba

…active active setup.

Updated with:
Presently Terraform Enterprise active active does not support the redis cluster protocol and hence no clustering should be enabled for a successful active active setup.

## Labels

- [ ] inaccuracy
- [ ] clarification
- [ ] new docs
- [ ] cosmetic bug - fixing broken text or markup
- [ ] enhancement - changing the website's behavior/layout
- [ ] api - requires an update to the [changelog](https://www.terraform.io/docs/cloud/api/changelog.html)

2021-07-15 14:02 UTC, laurapacilio commented
@eastebry Could you review this, or let me know who is the right person? Thank you!

2021-07-15 14:12 UTC, practicalint approved these changes
Yes, I think this is a helpful and valid edit. Thanks. Approved

2021-07-15 14:24 UTC, laurapacilio requested changes
Thank you for submitting this! I left a quick suggestion for you to review. Once you take a look, we can get this merged in.

2021-07-15 14:24 UTC, laurapacilio commented on content/source/docs/enterprise/before-installing/reference-architecture/azure.md
> +Presently Terraform Enterprise active active does not support the redis cluster protocol and hence no clustering should be enabled for a successful active active setup.
Just revising for active voice and to make sure we're reference Active/Active the same way throughout the page. 

```suggestion
Terraform Enterprise _Active/Active_ does not currently support the Redis cluster protocol, so you should not enable clustering for a successful _Active/Active_ setup.
```

2021-07-16 13:24 UTC, laurapacilio approved these changes

2021-07-16 13:25 UTC, merged