Update azure-ad.html.md
hashicorp/terraform-website pull request #1785
Opened 2021-07-26 12:31 UTC by abuxton

malformed markdown due to missing line break between content and list.

## Labels

- [ ] inaccuracy
- [ ] clarification
- [ ] new docs
- [ ] cosmetic bug - fixing broken text or markup
- [ ] enhancement - changing the website's behavior/layout
- [ ] api - requires an update to the [changelog](https://www.terraform.io/docs/cloud/api/changelog.html)

2021-07-26 12:31 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/terraform-website?pullRequest=1785)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/terraform-website?pullRequest=1785)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/terraform-website?pullRequest=1785).</sub>

2021-07-26 14:22 UTC, laurapacilio requested changes
Hi,

Thank you so much for submitting this fix! I'm suggesting a couple of additional changes that fix some other cosmetic issues with the text. Would you mind committing these as well? After you do that, I'll merge - thanks!

2021-07-26 14:22 UTC, laurapacilio commented on content/source/docs/cloud/users-teams-organizations/single-sign-on/azure-ad.html.md
>  1. We recomoned naming it "MemberOf", leaving the namespace blank, and potentially sourcing `user.assignedroles` as an easy starting point.
```suggestion

1. Navigate to the single sign-on page.
2. Edit step 2, "User Attributes & Claims."
    We recommend naming it "MemberOf", leaving the namespace blank, and potentially sourcing `user.assignedroles` as an easy starting point.
```

2021-07-26 14:22 UTC, laurapacilio commented on content/source/docs/cloud/users-teams-organizations/single-sign-on/azure-ad.html.md
>  1. We recomend naming the claim "Username", leaving the namespace blank, and sourcing something like `user.displayname` or `user.mailnickname`.
```suggestion
1. Navigate to the single sign-on page.
2. Edit step 2, "User Attributes & Claims."
    We recommend naming the claim "Username", leaving the namespace blank, and sourcing something like `user.displayname` or `user.mailnickname`.
```

2021-07-28 08:18 UTC, abuxton commented
@laurapacilio done thank you

2021-07-28 14:07 UTC, laurapacilio approved these changes

2021-07-28 14:08 UTC, merged