docs/plugin/framework: Update code examples for v0.3.0 breaking changes
hashicorp/terraform-website pull request #1862
Opened 2021-09-10 00:28 UTC by bflad

Closes hashicorp/terraform-plugin-framework#140

## Labels

- [x] inaccuracy
- [ ] clarification
- [ ] new docs
- [ ] cosmetic bug - fixing broken text or markup
- [ ] enhancement - changing the website's behavior/layout
- [ ] api - requires an update to the [changelog](https://www.terraform.io/docs/cloud/api/changelog.html)

2021-09-12 00:55 UTC, paddycarver requested changes

2021-09-12 00:55 UTC, paddycarver commented on content/source/docs/plugin/framework/accessing-values.html.md
>  		// TODO: handle error
This can probably just return, now.

2021-09-13 13:02 UTC, bflad commented on content/source/docs/plugin/framework/accessing-values.html.md
>  		// TODO: handle error
Indeed! Will fill that in.

2021-09-13 13:03 UTC, bflad commented on content/source/docs/plugin/framework/accessing-values.html.md
>  		// TODO: handle error
```suggestion
		return
```

2021-09-13 13:04 UTC, bflad commented on content/source/docs/plugin/framework/writing-state.html.md
>  		// TODO: handle error
```suggestion
		return
```

2021-09-13 13:04 UTC, bflad commented on content/source/docs/plugin/framework/writing-state.html.md
>  		// TODO: handle error
```suggestion
		return
```

2021-09-13 13:04 UTC, bflad commented on content/source/docs/plugin/framework/writing-state.html.md
>  		// TODO: handle error
```suggestion
		return
```

2021-09-14 04:30 UTC, paddycarver approved these changes
LGTM, let's do it. Nice work! 👍 🚀

2021-09-14 14:12 UTC, merged