Ab vmware aa docs
hashicorp/terraform-website pull request #1937
Opened 2021-11-02 16:56 UTC by amy-hashi

## Labels

- [ ] inaccuracy
- [ ] clarification
- [x] new docs
- [ ] cosmetic bug - fixing broken text or markup
- [ ] enhancement - changing the website's behavior/layout
- [ ] api - requires an update to the [changelog](https://www.terraform.io/docs/cloud/api/changelog.html)

This PR adds documentation around running TFE Active/Active on VMware.

2021-11-02 20:26 UTC, laurapacilio approved these changes
Thank you!

2021-11-03 18:45 UTC, jmariedee requested changes

2021-11-03 19:01 UTC, amy-hashi commented on content/source/docs/enterprise/before-installing/reference-architecture/vmware.md
> +We have tested Active/Active on VMWare internally on ESX version 7.0.1 and vCenter Server Appliance version 7.0.2.00200.
I'm not sure these are minimums, actually. I don't see any reason this wouldn't work on v6. I think maybe we could put a note that whatever the provider supports is good?

2021-11-03 19:01 UTC, amy-hashi commented on content/source/docs/enterprise/before-installing/reference-architecture/vmware.md
> +- Both virtual machines located in the same physical datacenter and on the same network. High amounts of network latency between the Terraform Enterprise virtual machines and the external services ma
Let's put that on the future list. It will actually function with pretty high network latency, it just runs really slowly.

2021-11-03 19:04 UTC, amy-hashi commented on content/source/docs/enterprise/install/active-active.html.md
> +Redis on VMware was tested with a virtual machine with 2 CPUs and 8 Gb of memory running Ubuntu 20.04. Both Redis v5 and v6 are supported.
I'm going to put a comment and link to the pre-install checklist. Then I vote we add a section there for the external services versions?

2021-11-03 19:05 UTC, amy-hashi commented on content/source/docs/enterprise/before-installing/reference-architecture/vmware.md
> +This guide will present the base _Active/Active_ mode first and then discuss the differences that alter the implementation into the _Standalone/Mounted Disk_ mode.
No particular reason. I can re-arrange.

2021-11-03 19:35 UTC, amy-hashi commented on content/source/docs/enterprise/before-installing/reference-architecture/vmware.md
> +You should back up and replicate the stateful external service (PostgreSQL and Blob Storage) to an offsite location to enable a disaster recovery or datacenter failover. You can use either the [Backu
fixed

2021-11-03 19:35 UTC, amy-hashi commented on content/source/docs/enterprise/before-installing/reference-architecture/vmware.md
> +You should back up and replicate the stateful external service (PostgreSQL and Blob Storage) to an offsite location to enable a disaster recovery or datacenter failover. You can use either the [Backu
fixed

2021-11-03 19:35 UTC, amy-hashi commented on content/source/docs/enterprise/before-installing/reference-architecture/vmware.md
> +This guide will present the base _Active/Active_ mode first and then discuss the differences that alter the implementation into the _Standalone/Mounted Disk_ mode.
done.

2021-11-03 19:38 UTC, amy-hashi commented on content/source/docs/enterprise/before-installing/reference-architecture/vmware.md
> +We have tested Active/Active on VMWare internally on ESX version 7.0.1 and vCenter Server Appliance version 7.0.2.00200.
fixed.

2021-11-05 19:13 UTC, jmariedee commented on content/source/docs/enterprise/before-installing/reference-architecture/vmware.md
> +This guide will present the base _Active/Active_ mode first and then discuss the differences that alter the implementation into the _Standalone/Mounted Disk_ mode.
This still says "This guide will present the base _Active/Active_ mode first and then discuss the differences that alter the implementation into the _Standalone/Mounted Disk_ mode."

2021-11-05 19:21 UTC, jmariedee approved these changes
LGTM! Thanks for tackling the supported OS docs at the same time.

2021-11-05 19:21 UTC, merged