Public provider curation api docs
hashicorp/terraform-website pull request #1951
Opened 2021-11-10 01:34 UTC by bethanyr

## Labels

- [ ] inaccuracy
- [ ] clarification
- [ ] new docs
- [ ] cosmetic bug - fixing broken text or markup
- [ ] enhancement - changing the website's behavior/layout
- [ ] api - requires an update to the [changelog](https://www.terraform.io/docs/cloud/api/changelog.html)

2021-11-15 22:18 UTC, laurapacilio requested changes
Hi! These are great already! I left a couple of suggestions. Let me know what you think - thank you!

2021-11-15 22:18 UTC, laurapacilio commented on content/source/docs/cloud/api/providers.html.md
> +When created, the public provider record will be available in the organization's registry provider list. You cannot create versions for public providers as they are maintained in the public registry.
```suggestion
When created, the public provider record will be available in the organization's registry provider list. You cannot create versions for public providers; you must use the versions available on the Terraform Registry.
```

2021-11-15 22:18 UTC, laurapacilio commented on content/source/docs/cloud/api/providers.html.md
> +`:name`              | The provider name that the deletion will affect.
```suggestion
`:namespace`         | The namespace of the provider that will be deleted.
`:name`              | The name of the provider that will be deleted.
```

2021-11-15 22:18 UTC, laurapacilio commented on content/source/docs/cloud/api/providers.html.md
> +[404][] | [JSON API error object][]                            | Provider not found or user not authorized
```suggestion
[404][] | [JSON API error object][]                            | Provider not found or user not authorized to perform action
```

2021-11-18 21:11 UTC, laurapacilio approved these changes
Approving so I don't block :-) We can press forward without my previous comments if necessary (though I do still have those recommendations!)

2021-11-19 21:21 UTC, bethanyr commented on content/source/docs/cloud/api/providers.html.md
> +- [Authentication](./index.html#authentication) is handled the same as all other Terraform Cloud endpoints.
I went ahead and deleted for now, we don't publish the public registry provider endpoints.

2021-11-19 21:21 UTC, bethanyr commented on content/source/docs/cloud/api/providers.html.md
> +Lists the providers that are available to a given organization.
thanks - I have updated.

2021-11-19 21:21 UTC, bethanyr commented on content/source/docs/cloud/api/providers.html.md
> +`q`                                 | **Optional.** A search query string.  Providers are searchable by name, namespace fields.
thanks - I have updated.

2021-11-19 21:26 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/terraform-website?pullRequest=1951)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/terraform-website?pullRequest=1951)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)


---
**15** out of **16** committers have signed the CLA.

- [x] p0pr0ck5
- [x] cam-stitt
- [x] jescalan
- [x] amy-hashi
- [x] laurapacilio
- [x] brandonc
- [x] ryanuber
- [x] polyglotdev
- [x] dylanegan
- [x] dstaley
- [x] anamahalo
- [x] zisom-hc
- [x] ykhemani
- [x] kmruddy
- [x] bethanyr
- [ ] hc-github-team-tf-core

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/terraform-website?pullRequest=1951).</sub>

2021-11-19 21:31 UTC, merged