Change wording for better understanding
hashicorp/terraform-website pull request #2134
Opened 2022-02-07 18:03 UTC by pabloehc

2022-02-07 18:03 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/terraform-website?pullRequest=2134)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/terraform-website?pullRequest=2134)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/terraform-website?pullRequest=2134).</sub>

2022-02-14 22:36 UTC, laurapacilio requested changes
Thank you! :-) Suggesting an edit to make it even clearer with active voice. @bflad Could you take a look at this to make sure my suggested change is technically correct?

2022-02-14 22:36 UTC, laurapacilio commented on content/plugin/sdkv2/schemas/schema-behaviors.mdx
>  the configuration.
```suggestion
If `Default` is specified, Terraform will use that value when this item is not set in
the configuration.
```

2022-02-15 15:14 UTC, bflad approved these changes
Looks good to me 🚀

2022-02-15 15:14 UTC, merged