Update Terraform Website documentation for the new Organization and Workspace Manage Run Task permissions
hashicorp/terraform-website pull request #2236
Opened 2022-04-12 11:46 UTC by tstormk

I've added documentation for the new Run Task permissions introduced in [TF-474 Run Task Permissions](https://docs.google.com/document/d/1WkQmRnXz4P6URNHf0xV9FR25ojcEWdmeRKDId7vJnnE/edit#).

2022-04-12 11:46 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/terraform-website?pullRequest=2236)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/terraform-website?pullRequest=2236)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/terraform-website?pullRequest=2236).</sub>

2022-04-13 00:11 UTC, hcrhall commented on content/cloud-docs/users-teams-organizations/permissions.mdx
> +- **Manage Workspace Run Tasks:** - Allows users to associate and unassociate run tasks in the workspace. Run Tasks are created at the Organization level, after which they can be manually associated
```suggestion
- **Manage Workspace Run Tasks:** - Allows users to associate or dissociate run tasks to the workspace. Run Tasks are created at the Organization level, after which they can be manually associated or dissociated to specific workspaces.
```

2022-04-13 00:12 UTC, hcrhall commented on content/cloud-docs/api-docs/run-tasks.mdx
> +To interact with run tasks on an organization, you need the [Manage Run Tasks permission](/cloud-docs/users-teams-organizations/permissions#manage-run-tasks). To associate and unassociate run tasks i
```suggestion
To interact with run tasks on an organization, you need the [Manage Run Tasks permission](/cloud-docs/users-teams-organizations/permissions#manage-run-tasks). To associate or dissociate run tasks in a workspace, you need the [Manage Run Task Associations permission](/cloud-docs/users-teams-organizations/permissions#general-workspace-permissions) on that particular workspace.
```

2022-04-13 00:17 UTC, hcrhall reviewed
A couple of minor suggestions from me. Do we need to update the **Workspace Admins** and **Fixed Permissions** sections in the [Permissions](content/cloud-docs/users-teams-organizations/permissions.mdx) markdown? 

I think it might be worth adding _Manage Workspace Run Tasks_ to both, but I am happy for you to be my guide @tstormk 😄

2022-04-13 02:04 UTC, glennsarti approved these changes
From a technical point of view, this looks good.  I'll leave the grammar etc. review to @laurapacilio

2022-04-13 18:35 UTC, laurapacilio commented on content/cloud-docs/users-teams-organizations/permissions.mdx
> +- **Manage Workspace Run Tasks:** - Allows users to associate and unassociate run tasks in the workspace. Run Tasks are created at the Organization level, after which they can be manually associated
```suggestion
- **Manage Workspace Run Tasks:** - Allows users to associate or dissociate run tasks in the workspace. Run Tasks are created at the organization level, after which you can manually associate or dissociate them to specific workspaces.
```

2022-04-13 18:37 UTC, laurapacilio requested changes
A language nit on a suggestion Ryan made and then --> On the actual Run Tasks page, I think we need to explain "association" and how users can do this from within the workspace.

https://www.terraform.io/cloud-docs/workspaces/settings/run-tasks#adding-run-tasks-to-a-workspace

I'm thinking probably it could be a subheading under "Adding Run Tasks to a Workspace"? Do we have the UI piece of this done yet?

2022-04-26 21:00 UTC, laurapacilio commented on content/cloud-docs/users-teams-organizations/permissions.mdx
> +- **Manage Workspace Run Tasks:** - Allows users to associate or dissociate run tasks in the workspace. Run Tasks are created at the organization level, after which you can manually associate or diss
```suggestion
- **Manage Workspace Run Tasks:** - Allows users to associate or dissociate run tasks with the workspace. Run Tasks are created at the organization level, after which you can manually associate or dissociate them with specific workspaces.
```

2022-04-26 21:03 UTC, laurapacilio commented
The "creating" of the run task which is described in the docs you linked is what is meant by associating the run task, so I'm not sure what section to add here. 

oh my, I'm so sorry about that. I see now that the language in the UI is "associate" and I don't know why that initially confused me. I think it may be because the title of that section is "Adding" and not "Associating". Perhaps we should change that section title to "Associating Run Tasks with a Workspace"? 

And then I just did a tiny language nit because I think we typically say "associate with" rather than "associate to".

2022-04-26 21:04 UTC, laurapacilio approved these changes
Pre-approving so I don't block you, but refer to my minor comments :-) Thank you!

2022-04-27 02:58 UTC, hcrhall commented
@tstormk I have just picked up that we need to also update the [requirements](https://www.terraform.io/cloud-docs/workspaces/settings/run-tasks#requirements) section in the workspace settings docs so that it draws attention to the new permissions.

2022-04-27 14:44 UTC, tstormk commented
@laurapacilio nothing to be sorry about! I've updated as requested.

@hcrhall Updated! Can you verify that the changes are OK?

2022-04-27 15:07 UTC, laurapacilio commented
Thank you! :-)  @tstormk also! Can you try merging with the master branch? I see the vercel is failing, and we can't merge until that successfully deploys. I'm wondering if it's because they made a change/update to something (on the website backend?) in master.

2022-04-28 11:04 UTC, tstormk commented
@laurapacilio Yep, it's updated now!

2022-04-29 04:45 UTC, hcrhall commented
> @laurapacilio nothing to be sorry about! I've updated as requested.
> 
> @hcrhall Updated! Can you verify that the changes are OK?

LGTM!

2022-05-03 08:27 UTC, merged